- name: variable in ansible
  hosts: mongodb
  # This is play level variables
  vars:
    COURSE: DevOps with AWS
    TRAINER: Sivakumar
    DURATION: 110HRS
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print variable
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
